language: node_js
node_js:
  - '12.13.1'

env:
  - CI=true
  - PUBLIC_URL=.

cache:
  directories:
    - node_modules

script:
  - yarn test --collect-coverage --verbose

after_success:
  - cat ./coverage/lcov.info | coveralls && rm -rf ./coverage

before_deploy:
  - yarn global add netlify-cli
  - yarn build

deploy:
  provider: script
  script: netlify deploy --site $NETLIFY_SITE_ID --auth $NETLIFY_ACCESS_TOKEN --prod --dir ./build
  skip_cleanup: true
  on:
    branch: master
